### ISSUE TITLE
Token generation request - Performance issue for Marklogic based authentication with concurrent users

### ISSUE THREAD

**Issue by MayuriSivanesan** [koopjs/koop-provider-marklogic#178]
We have used marklogic based authentication for our koop-provider application and have begun load testing of about 100 concurrent users. With every request the time taken to fetch the token gradually increases. Some of them taking nearly more than 70secs to complete token generation request. This causes request timeout error after about 24 concurrent requests through the koop provider. We have also added the diagnostic data for better understanding.
The REST endpoint we tried to access: https://myhost/marklogic/token
And the time taken to complete each response is shown as graph in the attached image
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/72431336/141065681-ce7de5d0-c2e5-4391-bd49-e1cd493555d9.png)
And this the error log we get on server multiple times for concurrent request
{"address":"<IP>","code":"ETIMEDOUT","errno":"ETIMEDOUT","level":"error","port":<PORT>,"syscall":"connect"}
{"level":"debug","message":"resolving connection error connectionInfo:"}
 {"level":"debug","message":{"error":true,"errorMsg":"connect ETIMEDOUT <IP>:<PORT>"}}
{"level":"debug","message":"response from connectClient: "}
{"level":"debug","message":{"error":true,"errorMsg":"connect ETIMEDOUT <IP>:<PORT>"}}
{"level":"debug","message":"MarkLogic error"}
Error: connect ETIMEDOUT <IP>:<PORT>
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
   errno: 'ETIMEDOUT',
   code: 'ETIMEDOUT',
   syscall: 'connect',
   address: '<IP>',
   port: <PORT>
 }
Error: connect ETIMEDOUT <IP>:<PORT>
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
   errno: 'ETIMEDOUT',
   code: 'ETIMEDOUT',
   syscall: 'connect',
   address: '<IP>',
   port: <PORT>
 }
 {"level":"debug","message":"error occurred:"}

**Comment by MayuriSivanesan** [comment]
Changed authentication to file-based authentication which reduces the request time.

**Comment by jkerr5** [comment]
We should keep this issue open as switching to file-based auth is not an option for everyone.

**Comment by mitchshepherd** [comment]
Hello @MayuriSivanesan. Are you still using Koop with MarkLogic? Can you provide more information for what type of authentication you require?
