### ISSUE TITLE
Resolve error for Geometric query where geometryType=esriGeometryPoint

### ISSUE THREAD

**Issue by jmamanpara** [koopjs/koop-provider-marklogic#48]
Query : /marklogic/GDeltGKG/FeatureServer/3/query?geometryType=esriGeometryPoint&geometry=-122.2465038,37.5073428

Stacktarce : 

Error: bbox must be an Array of 4 or 6 numbers
    at Object.validateBBox (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/@turf/helpers/main.js:694:55)
    at bboxPolygon (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/@turf/bbox-polygon/main.js:20:13)
    at module.exports (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/winnow/dist/geometry/transform-array.js:3:10)
    at normalizeGeometry (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/winnow/dist/options/normalizeOptions.js:66:16)
    at Object.prepare (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/winnow/dist/options/index.js:23:15)
    at Model.getData (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/marklogic.js:25:28)
    at /Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/koop/dist/models/index.js:13:14
    at Cache.retrieve (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/koop-cache-memory/dist/index.js:75:38)
    at Model.pull (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/koop/dist/models/index.js:9:14)
    at Controller.Geoservices.featureServer (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/koop-output-geoservices/index.js:7:14)
    at Layer.handle [as handle_request] (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/layer.js:95:5)
    at next (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/layer.js:95:5)
    at /Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/index.js:281:22
    at param (/Projects/github/ESRI/koop44/koop-provider-marklogic/build/koop/node_modules/express/lib/router/index.js:354:14)

**Comment by jkerr5** [comment]
This looks like a bug in koop so I'll convert this to an issue on feature server.

According the Esri documentation https://resources.arcgis.com/en/help/rest/apiref/fsservicequery.html this should be supported.

**Comment by jkerr5** [comment]
Submitted https://github.com/koopjs/FeatureServer/issues/76

**Comment by BillFarber** [comment]
This is working now on the current develop branch using the latest @koopjs libraries, so it will be working in the next release.
